# Generated by Django 2.1.7 on 2019-03-19 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons_departaments',
            fields=[
                ('persons_departaments_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ItemCategory')),
                ('persons_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Persons')),
            ],
        ),
        migrations.CreateModel(
            name='Persons_media',
            fields=[
                ('persons_media_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('item_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ItemCategory')),
                ('persons_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Persons')),
            ],
        ),
        migrations.CreateModel(
            name='Persons_role',
            fields=[
                ('persons_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ItemCategory')),
                ('persons_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Persons')),
            ],
        ),
    ]
