# Generated by Django 2.1.7 on 2019-03-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='date_joined',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last_modified',
            new_name='update_time',
        ),
    ]
