# Generated by Django 2.1.7 on 2019-03-20 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_persons_departaments_persons_media_persons_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons_Contacts',
            fields=[
                ('contact_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ItemCategory')),
                ('persons_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Persons')),
            ],
        ),
    ]
