# Generated by Django 2.1.7 on 2019-03-12 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCategory', models.IntegerField(primary_key=True, serialize=False)),
                ('nameCategory', models.CharField(max_length=255)),
                ('active', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('item_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_item', models.CharField(max_length=255)),
                ('active', models.PositiveSmallIntegerField()),
                ('category_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Category')),
            ],
        ),
    ]
