# Generated by Django 2.1.7 on 2019-04-30 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190421_0504'),
        ('login', '0003_persons_contacts'),
    ]

    operations = [
    ]
